server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/udemy
    password: 123

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

security:
  jwt:
   secret-key: 5Nvrft3ijR0yDefrfJfzYQzwjxDjpXiMQ0B3tLvqf5RzjXyCkWXNqrNJftPuQaDRhLNz


